name: CIWorkflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Cache
      uses: actions/cache@v4.2.2
      with:
        path: ~/.npm
        key: buildCache
    - name: Install packages
      run: npm ci
    - name: Execute tests
      run: npm test -- --coverage
      env:
        CI: true
    - name: Upload code coverage
      uses: actions/upload-artifact@v4.6.1
      with:
        name: codecoverage
        path: coverage
    - name: build
      run: npm run build
    - name: Upload build files
      uses: actions/upload-artifact@v4.6.1
      with:
        name: build
        path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://unadvised-leaf.surge.sh
    steps:
    - name: Download the Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: build
    - name: deploy to surge
      run: npx surge --project ‘.’ --domain http://unadvised-leaf.surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
