name: CIWorkflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Cache
      uses: actions/cache@v4.2.2
      with:
        path: ~/.npm
        key: buildCache
    - name: Install packages
      run: npm ci
    - name: Execute tests
      run: npm test -- --coverage
      env:
        CI: true
    - name: Upload code coverage
      uses: actions/upload-artifact@v4.6.1
      with:
        name: codecoverage
        path: coverage
    - name: build
      run: npm run build
    - name: Upload build files
      uses: actions/upload-artifact@v3.6.1
      with:
        name: build
        path: build
